#Take the correlation matrices generated by Spotlight and try to calculate the mean correlation across patients.



suppressPackageStartupMessages({
library(SPOTlight)
library(tidyverse)
library(glue)
})

#Data is here:
data_dir<-"/directflow/SCCGGroupShare/projects/venchi/HN/HN_2022_new_demultiplexed_data/Visium/Seurat/data"

print("load in samples")
samples <- c("HN230620A", "HN021219A", "HN120819A", "HN200519A") 
i <- as.integer(commandArgs(trailingOnly=TRUE)[1])
sample_name <- samples[i]

print("start with tcells")
group_name <- "tcell"
site<-"LN"


print("read .csv file")

x<-read.csv(file = str_glue("{data_dir}/{sample_name}_{group_name}_deconmatrix_{site}_new.csv"), header = TRUE)

print("generate cor matrix")
#Get rid of column at the front of data.frame
x$X<-NULL
#Change to a matrix
x<-data.matrix(x)
#Calculate matrix
x.cor<-cor(x)

#print("extract rows for Expanding and Non.Expanding")
#clone.rows<-c("Expanding", "Non.Expanding")
#Now try and subet the matrix
#data.mod<-x.cor[rownames(x.cor) %in% clone.rows, ]

print("save the correlation matrix")
write.csv(x.cor, file = str_glue("{data_dir}/{sample_name}_{group_name}_{site}_cor_matrix.csv"))

print("bcells")
group_name<-"bcell"

print("read .csv file")

x<-read.csv(file = str_glue("{data_dir}/{sample_name}_{group_name}_deconmatrix_{site}_new.csv"), header = TRUE)

print("generate cor matrix")
#Get rid of column at the front of data.frame
x$X<-NULL
#Change to a matrix
x<-data.matrix(x)
#Calculate matrix
x.cor<-cor(x)

#print("extract rows for Expanding and Non.Expanding")
#clone.rows<-c("Expanding", "Non.Expanding")
#Now try and subet the matrix
#data.mod<-x.cor[rownames(x.cor) %in% clone.rows, ]

print("save the correlation matrix")
write.csv(x.cor, file = str_glue("{data_dir}/{sample_name}_{group_name}_{site}_cor_matrix.csv"))

print("Monocytes")
group_name<-"mono"

print("read .csv file")

x<-read.csv(file = str_glue("{data_dir}/{sample_name}_{group_name}_deconmatrix_{site}_new.csv"), header = TRUE)

print("generate cor matrix")
#Get rid of column at the front of data.frame
x$X<-NULL
#Change to a matrix
x<-data.matrix(x)
#Calculate matrix
x.cor<-cor(x)

#print("extract rows for Expanding and Non.Expanding")
#clone.rows<-c("Expanding", "Non.Expanding")
#Now try and subet the matrix
#data.mod<-x.cor[rownames(x.cor) %in% clone.rows, ]

print("save the correlation matrix")
write.csv(x.cor, file = str_glue("{data_dir}/{sample_name}_{group_name}_{site}_cor_matrix.csv"))

print("other")
group_name<-"other"

print("read .csv file")

x<-read.csv(file = str_glue("{data_dir}/{sample_name}_{group_name}_deconmatrix_{site}_new.csv"), header = TRUE)

print("generate cor matrix")
#Get rid of column at the front of data.frame
x$X<-NULL
#Change to a matrix
x<-data.matrix(x)
#Calculate matrix
x.cor<-cor(x)

#print("extract rows for Expanding and Non.Expanding")
#clone.rows<-c("Expanding", "Non.Expanding")
#Now try and subet the matrix
#data.mod<-x.cor[rownames(x.cor) %in% clone.rows, ]

print("save the correlation matrix")
write.csv(x.cor, file = str_glue("{data_dir}/{sample_name}_{group_name}_{site}_cor_matrix.csv"))

print("NK")
group_name<-"NK"

print("read .csv file")

x<-read.csv(file = str_glue("{data_dir}/{sample_name}_{group_name}_deconmatrix_{site}_new.csv"), header = TRUE)

print("generate cor matrix")
#Get rid of column at the front of data.frame
x$X<-NULL
#Change to a matrix
x<-data.matrix(x)
#Calculate matrix
x.cor<-cor(x)

#print("extract rows for Expanding and Non.Expanding")
#clone.rows<-c("Expanding", "Non.Expanding")
#Now try and subet the matrix
#data.mod<-x.cor[rownames(x.cor) %in% clone.rows, ]

print("save the correlation matrix")
write.csv(x.cor, file = str_glue("{data_dir}/{sample_name}_{group_name}_{site}_cor_matrix.csv"))




